### ISSUE TITLE
extra white background in firefox

### ISSUE THREAD

**Issue by thecristen** [danielstern/range.css#24]
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/2136286/60042354-86574e80-968b-11e9-8707-b1beed9298a2.png">

Only noticable for skinny ranges.

**Comment by thecristen** [comment]
Seems to be solved by adding a transparent background-color to the input, but I'm not sure how this affects the display in the other browsers.

```css
input[type=range] {
  /* ... */
  background-color: transparent;
}
```
