### ISSUE TITLE
add style for disabled sliders

### ISSUE THREAD

**Issue by milahu** [danielstern/range.css#31]
i use `<input type="slider" disabled>` for output values

disabled sliders are read-only, and should have a different style than writable sliders

for example:

```css
/* disable color + cursor */
input[type=range][disabled]::-webkit-slider-thumb {
  background: grey;
  cursor: default;
}
input[type=range][disabled]::-webkit-slider-runnable-track {
  cursor: default;
}

/* disable hover color */
input[type=range][disabled]:hover::-webkit-slider-runnable-track {
  background: white;
}
input[type=range][disabled]:hover::-webkit-slider-thumb {
  background: grey;
}

/* hover color */
input[type=range]:hover::-webkit-slider-runnable-track {
  background: lightgray;
}
```
