### ISSUE TITLE
add style for hover effect

### ISSUE THREAD

**Issue by milahu** [danielstern/range.css#32]
for example:

```css
/* hover color */
input[type=range]:hover::-webkit-slider-runnable-track {
  background: lightgray;
}
input[type=range]:hover::-webkit-slider-thumb {
  background: darkblue;
}
```
